;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        cljr-add-missing-libspec
        hydra-cljr-code-menu/cljr-promote-function
        indent-for-tab-command
        org-self-insert-command
        sp-backward-delete-char
        sp-forward-slurp-sexp
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        cider-eval-last-sexp
        crux-move-beginning-of-line
        end-of-buffer
        handle-switch-frame
        helm-M-x
        prelude-smart-open-line
        sp-backward-sexp
        sp-forward-barf-sexp
        ))
